---
compose_project_name: "timemachine"
docker_volume_dirs:
  timemachine:
    - "{{ rclone_mount_dir }}"
  promtail:
    - "/mnt/{{ compose_project_name }}/promtail/config"
docker_user_id:
  timemachine: 1000
docker_group_id:
  timemachine: 1000
