---
services:
  vault:
    image: hashicorp/vault:latest@sha256:4e33b126a59c0c333b76fb4e894722462659a6bec7c48c9ee8cea56fccfd2569
    volumes:
      - "{{ docker_volume_dirs.vault[0].path }}:/vault/config"
      - "{{ docker_volume_dirs.vault[1].path }}:/vault/file"
      - "{{ docker_volume_dirs.vault[2].path }}:/vault/logs"
      - "{{ docker_volume_dirs.vault[3].path }}:/vault/plugins"
    ports:
      - "{{ vault.port }}:{{ vault.internal_port }}"
    cap_add:
      - IPC_LOCK
    restart: always
    command: [vault, server, -config, /vault/config/config.hcl]
  opconnect_api:
    image: 1password/connect-api:latest@sha256:e915c0c843972f02b0e7e2de502bda8bd4a092288b3f1866098a857bd715a281
    volumes:
      - "{{ docker_volume_dirs.opconnect[0].path }}/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - data:/home/opuser/.op/data
    ports:
      - "{{ opconnect.api.port }}:{{ opconnect.api.internal_port }}"
    restart: always
  opconnect_sync:
    image: 1password/connect-sync:latest@sha256:6297ca6136c0f0fb096bc64c49e1bc8df2aab35282ebff8c7bb60745ef176d0d
    volumes:
      - "{{ docker_volume_dirs.opconnect[0].path }}/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - data:/home/opuser/.op/data
    ports:
      - "{{ opconnect.sync.port }}:{{ opconnect.sync.internal_port }}"
    restart: always

volumes:
  data:
