---
services:
  vault:
    image: hashicorp/vault:latest@sha256:c2f666266f383d2cf424d86b8bb8ce7d065562173ffec2b476d762943608bb55
    volumes:
      - "{{ docker_volume_dirs.vault[0].path }}:/vault/config"
      - "{{ docker_volume_dirs.vault[1].path }}:/vault/file"
      - "{{ docker_volume_dirs.vault[2].path }}:/vault/logs"
      - "{{ docker_volume_dirs.vault[3].path }}:/vault/plugins"
    ports:
      - "{{ vault.port }}:{{ vault.internal_port }}"
    cap_add:
      - IPC_LOCK
    restart: always
    command: [vault, server, -config, /vault/config/config.hcl]
  opconnect_api:
    image: 1password/connect-api:latest@sha256:656e4b10df83ca258d8a75b2a051f7c06dd608212f8ae5ba4722e3fe164099d3
    volumes:
      - "{{ docker_volume_dirs.opconnect[0].path }}/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - data:/home/opuser/.op/data
    ports:
      - "{{ opconnect.api.port }}:{{ opconnect.api.internal_port }}"
    restart: always
  opconnect_sync:
    image: 1password/connect-sync:latest@sha256:a760350c941a3e7c98dd66394e9fc3c7e68b6a0a2246a837c74084e534f75f6b
    volumes:
      - "{{ docker_volume_dirs.opconnect[0].path }}/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - data:/home/opuser/.op/data
    ports:
      - "{{ opconnect.sync.port }}:{{ opconnect.sync.internal_port }}"
    restart: always

volumes:
  data:
