---
version: "3"
services:
  ghost:
    image: ghost:latest@sha256:1582ff7d419839eea2d5d75867703a6344f0df818f1b31680fe68b2c77940ea7
    volumes:
      - "{{ docker_volume_dirs.ghost[0] }}/config.production.json:/var/lib/ghost/config.production.json"
      - "{{ docker_volume_dirs.ghost[1] }}:/var/lib/ghost/content"
      - "{{ docker_volume_dirs.ghost[2] }}:/var/lib/ghost/node_modules"
    ports:
      - "{{ compose_project_ports[0] }}:2368"
    restart: always
  promtail:
    image: grafana/promtail:latest@sha256:51346af8682f7a664affaca4f34a62f5a4f0f83ace9931df94590375a94ff8f1
    restart: always
    volumes:
      - /var/log/cloudflared.log:/var/log/cloudflared.log:ro
      - /var/log/journal:/var/log/journal:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ docker_volume_dirs.promtail[0] }}/config.yaml:/etc/promtail/config.yaml"
    command: -config.file=/etc/promtail/config.yaml
