---
version: "3"
services:
  ghost:
    image: ghost:latest@sha256:b7e8380d870369ddff882873ff63ee7ce013d382e81cf97adbe26a4d13daf38b
    volumes:
      - "{{ docker_volume_dirs.ghost[0] }}/config.production.json:/var/lib/ghost/config.production.json"
      - "{{ docker_volume_dirs.ghost[1] }}:/var/lib/ghost/content"
      - "{{ docker_volume_dirs.ghost[2] }}:/var/lib/ghost/node_modules"
    ports:
      - "{{ compose_project_ports[0] }}:2368"
    restart: always
  promtail:
    image: grafana/promtail:latest@sha256:6cfa64ec432b24a912d640e2edb940eeae2666f61861a66c121d763dd7241381
    restart: always
    volumes:
      - /var/log/cloudflared.log:/var/log/cloudflared.log:ro
      - /var/log/journal:/var/log/journal:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ docker_volume_dirs.promtail[0] }}/config.yaml:/etc/promtail/config.yaml"
    command: -config.file=/etc/promtail/config.yaml
